FROM ubuntu
MAINTAINER github/gklingler

RUN apt-get update
RUN apt-get install -y mesa-utils libxcursor1 libxrandr2

# install nvidia driver
RUN apt-get install -y binutils
ARG NVIDIA_DRIVER
ADD ${NVIDIA_DRIVER} /tmp/NVIDIA-DRIVER.run
RUN sh /tmp/NVIDIA-DRIVER.run -a -N --ui=none --no-kernel-module && \
    ls -la /tmp/NVIDIA-DRIVER.run

ADD UnityTest /UnityTest
